export const ADD_SELECTED_IMAGE = 'ADD_SELECTED_IMAGE';
export const DELETE_SELECTED_IMAGE = 'DELETE_SELECTED_IMAGE';
export const SET_IMAGES = 'SET_IMAGES';
export const SET_PAGE_INFO = 'SET_PAGE_INFO';
export const FETCHING_IMAGES = 'FETCHING_IMAGES';
export const SET_THEME = 'SET_THEME';